// <auto-generated />
namespace Rebbit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FirstUpload : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstUpload));
        
        string IMigrationMetadata.Id
        {
            get { return "201705170343336_FirstUpload"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
